export const staticPosts = [
  { id: 1, userId: 1, title: "sunt aut facere repellat", body: "quia et suscipit\nsuscipit recusandae consequuntur..." },
  { id: 2, userId: 1, title: "qui est esse", body: "est rerum tempore vitae\nsequi sint nihil..." },
  { id: 3, userId: 1, title: "ea molestias quasi", body: "et iusto sed quo iure voluptatem occaecati..." },
  { id: 4, userId: 1, title: "eum et est occaecati", body: "ullam et saepe reiciendis voluptatem..." },
  { id: 5, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 6, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 7, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 8, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 9, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 10, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 11, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 12, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 13, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 14, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 15, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 16, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 17, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 18, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 19, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 20, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 21, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 22, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 23, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
  { id: 24, userId: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed..." },
];